# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "..", "/nsswitch_service"

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apt-get update
    apt-get install -y curl
  SHELL

  config.vm.provision "shell", privileged: false, path: "install_rust_and_build.sh"

  config.vm.provision "shell", privileged: true, path: "install_loopback_example.sh"
end
