# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "..", "/nsswitch_service"

  # Install Rust prerequisites.
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apt-get update
    apt-get install -y curl gcc
  SHELL

  # Install Rust.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    curl https://sh.rustup.rs -sSf | sh -- /dev/stdin -y
  SHELL

  # Build and unit-test the crate.
  config.vm.provision "shell", privileged: false, path: "build.sh"

  # Install the example library for further integration testing.
  # So far we're doing that manually.
  config.vm.provision "shell", privileged: true, path: "install_loopback_example.sh"
end
